name: Publish Extension

on:
  push:
    branches:
      - main  # trigger the action when a commit is made to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Package Extension
        run: npx vsce package

      - name: Publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        run: npx vsce publish --yarn --pat $VSCE_TOKEN
